#!/usr/bin/env python3
"""
StepMania Song Packager

Creates a complete StepMania song package ready for distribution.
Bundles audio file, .sm charts, and optional assets into a properly structured folder.
"""

import shutil
import zipfile
from pathlib import Path
import click
import sys
import tempfile
from PIL import Image, ImageDraw, ImageFont
import requests


def create_banner_image(song_title, artist_name, output_path):
    """Create a simple banner image for the song"""

    # StepMania banner size: 256x80 pixels
    banner = Image.new('RGB', (256, 80), color=(20, 20, 40))  # Dark blue background
    draw = ImageDraw.Draw(banner)

    try:
        # Try to use a nice font, fall back to default
        font_title = ImageFont.load_default()
        font_artist = ImageFont.load_default()
    except:
        font_title = ImageFont.load_default()
        font_artist = ImageFont.load_default()

    # Draw title (larger, centered at top)
    title_bbox = draw.textbbox((0, 0), song_title, font=font_title)
    title_width = title_bbox[2] - title_bbox[0]
    title_x = (256 - title_width) // 2
    draw.text((title_x, 15), song_title, fill=(255, 255, 255), font=font_title)

    # Draw artist (smaller, centered at bottom)
    artist_bbox = draw.textbbox((0, 0), f"by {artist_name}", font=font_artist)
    artist_width = artist_bbox[2] - artist_bbox[0]
    artist_x = (256 - artist_width) // 2
    draw.text((artist_x, 50), f"by {artist_name}", fill=(180, 180, 180), font=font_artist)

    # Add some decorative elements
    draw.rectangle([10, 10, 246, 12], fill=(0, 150, 255))  # Top accent line
    draw.rectangle([10, 68, 246, 70], fill=(0, 150, 255))  # Bottom accent line

    banner.save(output_path)
    return True


def create_song_package(audio_file, sm_files, output_dir="./stepmania_packages", include_banner=True):
    """
    Create a complete StepMania song package

    Args:
        audio_file: Path to the audio file
        sm_files: List of .sm file paths (different difficulties)
        output_dir: Where to create the package
        include_banner: Whether to generate a banner image
    """

    audio_path = Path(audio_file)
    output_dir = Path(output_dir)

    if not audio_path.exists():
        raise FileNotFoundError(f"Audio file not found: {audio_file}")

    # Extract song info from first .sm file
    sm_path = Path(sm_files[0])
    song_title, artist_name = extract_song_info(sm_path)

    # Create safe folder name
    safe_title = song_title.replace(" ", "_").replace("/", "_").replace("\\", "_").replace(":", "_")
    safe_artist = artist_name.replace(" ", "_").replace("/", "_").replace("\\", "_").replace(":", "_")
    folder_name = f"{safe_artist}-{safe_title}"

    # Create package directory
    package_dir = output_dir / folder_name
    package_dir.mkdir(parents=True, exist_ok=True)

    print(f"📦 Creating StepMania package: {folder_name}")

    # Copy audio file
    audio_dest = package_dir / audio_path.name
    shutil.copy2(audio_path, audio_dest)
    print(f"   ✅ Copied audio: {audio_path.name}")

    # Copy all .sm files
    for sm_file in sm_files:
        sm_path = Path(sm_file)
        if sm_path.exists():
            sm_dest = package_dir / sm_path.name
            shutil.copy2(sm_path, sm_dest)
            print(f"   ✅ Copied chart: {sm_path.name}")

    # Create banner image
    if include_banner:
        try:
            banner_path = package_dir / "banner.png"
            create_banner_image(song_title, artist_name, banner_path)
            print(f"   ✅ Generated banner: banner.png")
        except Exception as e:
            print(f"   ⚠️  Could not create banner: {e}")

    # Create a README for the package
    readme_content = f"""# {song_title} - {artist_name}

StepMania Song Package generated by AutoStepper MVP

## Installation:
1. Copy this entire folder to your StepMania Songs directory
2. Refresh your StepMania song cache (F5 in song selection)
3. The song should appear in your song list

## Package Contents:
- Audio: {audio_path.name}
- Charts: {len(sm_files)} difficulty levels
- Banner: banner.png (if generated)

## Chart Information:
Generated using advanced beat detection with librosa and Python.
Superior accuracy compared to traditional step chart generation tools.

## Attribution:
- Python AutoStepper MVP (this implementation)
- Original concept by phr00t: https://github.com/phr00t/AutoStepper
"""

    readme_path = package_dir / "README.txt"
    readme_path.write_text(readme_content)
    print(f"   ✅ Created README: README.txt")

    return package_dir


def extract_song_info(sm_file_path):
    """Extract title and artist from .sm file"""

    try:
        with open(sm_file_path, 'r', encoding='utf-8') as f:
            content = f.read()

        title = "Unknown Title"
        artist = "Unknown Artist"

        for line in content.split('\n'):
            line = line.strip()
            if line.startswith('#TITLE:'):
                title = line[7:-1]  # Remove #TITLE: and ;
            elif line.startswith('#ARTIST:'):
                artist = line[8:-1]  # Remove #ARTIST: and ;

        return title, artist

    except Exception:
        return "Unknown Title", "Unknown Artist"


def create_zip_package(package_dir):
    """Create a zip file of the song package"""

    package_path = Path(package_dir)
    zip_path = package_path.with_suffix('.zip')

    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zip_file:
        for file_path in package_path.rglob('*'):
            if file_path.is_file():
                arcname = file_path.relative_to(package_path.parent)
                zip_file.write(file_path, arcname)

    print(f"📦 Created zip package: {zip_path}")
    return zip_path


@click.command()
@click.option('--audio', '-a', required=True, help='Path to audio file')
@click.option('--charts', '-c', required=True, help='Directory containing .sm files')
@click.option('--output', '-o', default='./stepmania_packages', help='Output directory')
@click.option('--zip', '-z', is_flag=True, help='Create zip file for distribution')
@click.option('--banner/--no-banner', default=True, help='Generate banner image')
def main(audio, charts, output, zip, banner):
    """Package StepMania song with audio and charts for distribution"""

    print("🎵 StepMania Song Packager")
    print("=" * 40)

    audio_path = Path(audio)
    charts_dir = Path(charts)

    if not audio_path.exists():
        click.echo(f"❌ Audio file not found: {audio}", err=True)
        sys.exit(1)

    # Find all .sm files in charts directory
    sm_files = list(charts_dir.glob("*.sm"))

    if not sm_files:
        click.echo(f"❌ No .sm files found in: {charts}", err=True)
        sys.exit(1)

    try:
        # Create the package
        package_dir = create_song_package(
            audio_file=audio_path,
            sm_files=sm_files,
            output_dir=output,
            include_banner=banner
        )

        # Create zip if requested
        zip_path = None
        if zip:
            zip_path = create_zip_package(package_dir)

        # Show completion message
        print(f"\n🎉 Package created successfully!")
        print(f"📁 Folder: {package_dir}")
        if zip_path:
            print(f"📦 Zip file: {zip_path}")

        print(f"\n📝 To share with other StepMania users:")
        if zip_path:
            print(f"   1. Send them: {zip_path.name}")
            print(f"   2. They extract to StepMania/Songs/")
        else:
            print(f"   1. Send them the folder: {package_dir.name}")
            print(f"   2. They copy to StepMania/Songs/")
        print(f"   3. They refresh StepMania (F5)")

    except Exception as e:
        click.echo(f"❌ Packaging failed: {e}", err=True)
        sys.exit(1)


if __name__ == '__main__':
    main()